# Generated by Django 3.1 on 2020-10-06 09:48

from datetime import timedelta

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0016_workshop_approving_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="duration",
            field=models.DurationField(default=timedelta()),
            preserve_default=False,
        ),
    ]
