# Generated by Django 3.1.2 on 2020-10-15 18:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workshops", "0027_auto_20201015_1557"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buildingblocktemplate",
            options={
                "permissions": [
                    ("view_field_created_by_buildingblocktemplate", "Can view created by field of templates")
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="workshop",
            options={
                "permissions": [
                    ("view_all_workshop", "Can view all workshops"),
                    ("change_all_workshop", "Can change all workshops"),
                    ("request_publication_workshop", "Can request publication of workshops"),
                    ("publish_workshop", "Can publish of workshops"),
                    ("unpublish_workshop", "Can unpublish of workshops"),
                    ("view_to_be_published_workshops", "Can view the to be published workshops"),
                    ("view_field_created_by_workshop", "Can view created by field of workshops"),
                    ("view_field_is_sensitive_workshop", "Can view is sensitive field of workshops"),
                ]
            },
        ),
        migrations.AddField(
            model_name="buildingblocktemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buildingblocktemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workshops_buildingblocktemplate_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="buildingblocktemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
