# Generated by Django 3.1.2 on 2020-10-16 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0029_workshop_themes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workshop",
            name="theme",
        ),
    ]
