# Generated by Django 3.1.2 on 2020-10-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_ckeditorfile_content_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ckeditorfile",
            name="created_by",
        ),
    ]
