# Generated by Django 3.1.2 on 2021-04-27 13:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0034_auto_20210324_1514"),
        ("files", "0003_remove_ckeditorfile_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="ckeditorfile",
            name="workshop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="workshops.workshop",
            ),
        ),
        migrations.AlterField(
            model_name="ckeditorfile",
            name="file",
            field=models.FileField(
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "bmp",
                            "webp",
                            "tiff",
                            "odt",
                            "doc",
                            "docx",
                            "pdf",
                        ]
                    )
                ],
            ),
        ),
    ]
