# Generated by Django 3.1 on 2020-09-10 13:37

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('duration', models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=60)), django.core.validators.MaxValueValidator(datetime.timedelta(days=7))])),
                ('description', models.TextField()),
                ('necessities', models.TextField()),
                ('is_sensitive', models.BooleanField(default=False)),
                ('workshop_status_type', models.CharField(choices=[('PRIVATE', 'Privé'), ('PUBLICATION_REQUESTED', 'Publicatie aangevraagd'), ('PUBLISHED', 'Gepubliceerd')], default='PRIVATE', max_length=30)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='workshops.theme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuildingBlockTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=60)), django.core.validators.MaxValueValidator(datetime.timedelta(days=1))])),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('building_block_type', models.CharField(choices=[('THEMATIC', 'Inhoud'), ('METHODIC', 'Werkvorm')], max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='workshops.category')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='workshops.theme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuildingBlockInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=60)), django.core.validators.MaxValueValidator(datetime.timedelta(days=1))])),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='workshops.category')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='workshops.buildingblocktemplate')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='workshops.theme')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='building_blocks', to='workshops.workshop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
