# Generated by Django 3.0.8 on 2020-07-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='theme',
        ),
        migrations.AddField(
            model_name='workshop',
            name='theme',
            field=models.ManyToManyField(to='workshops.Theme'),
        ),
    ]
