# Generated by Django 3.0.8 on 2020-07-31 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="workshop", name="theme",),
        migrations.AddField(
            model_name="workshop",
            name="theme",
            field=models.ForeignKey(
                default="594862ca-f1cd-4bf1-b408-0fbaa210ba54",
                on_delete=django.db.models.deletion.CASCADE,
                to="workshops.Theme",
            ),
            preserve_default=False,
        ),
    ]
