# Generated by Django 3.1 on 2020-08-24 21:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_auto_20200731_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingBlockTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('building_block_type', models.CharField(choices=[('THEMATIC', 'Thematisch'), ('METHODIC', 'Methodisch')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='workshop',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='workshops.theme'),
        ),
        migrations.CreateModel(
            name='BuildingBlockInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='workshops.buildingblocktemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
