# Generated by Django 3.1 on 2020-08-25 09:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_auto_20200824_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingblockinstance',
            name='duration',
            field=models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=60)), django.core.validators.MaxValueValidator(datetime.timedelta(days=1))]),
        ),
        migrations.AlterField(
            model_name='buildingblocktemplate',
            name='duration',
            field=models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=60)), django.core.validators.MaxValueValidator(datetime.timedelta(days=1))]),
        ),
    ]
