# Generated by Django 3.1 on 2020-08-28 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingblockinstance',
            name='category',
            field=models.ForeignKey(default='787d75d3-689c-4dff-b3ae-cc0cedc63717', on_delete=django.db.models.deletion.RESTRICT, to='workshops.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildingblocktemplate',
            name='category',
            field=models.ForeignKey(default='787d75d3-689c-4dff-b3ae-cc0cedc63717', on_delete=django.db.models.deletion.RESTRICT, to='workshops.category'),
            preserve_default=False,
        ),
    ]
