# Generated by Django 3.1 on 2020-08-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0008_auto_20200828_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingblockinstance',
            name='short_description',
            field=models.CharField(default='Some random description', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildingblocktemplate',
            name='short_description',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
