# Generated by Django 3.1 on 2020-10-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0008_remove_workshop_is_sensitive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
