# Generated by Django 3.1 on 2020-09-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0009_auto_20200904_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='workshop_status_type',
            field=models.CharField(choices=[('PRIVATE', 'Privé'), ('PUBLICATION REQUESTED', 'Publicatie aangevraagd'), ('PUBLISHED', 'Gepubliceerd')], default='PRIVATE', max_length=30),
        ),
    ]
