# Generated by Django 3.1 on 2020-08-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0009_auto_20200828_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='is_sensitive',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
