# Generated by Django 3.1 on 2020-10-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0015_auto_20201005_1432"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="approving_team",
            field=models.CharField(
                blank=True, choices=[("GROUP1", "Ploeg 1"), ("GROUP2", "Ploeg 2")], max_length=30, null=True
            ),
        ),
    ]
