# Generated by Django 3.1 on 2020-10-07 07:50

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0017_auto_20201006_0948"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
