# Generated by Django 3.1 on 2020-10-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0018_auto_20201007_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'permissions': [('view_to_be_published_workshops', 'Can view the to be published workshops')]},
        ),
    ]
