# Generated by Django 3.1 on 2020-10-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0018_auto_20201007_0750"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="necessities",
            field=models.TextField(blank=True),
        ),
    ]
