# Generated by Django 3.1 on 2020-10-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0019_auto_20201008_0723"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingblocktemplate",
            name="is_disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="category",
            name="is_disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="theme",
            name="is_disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workshop",
            name="is_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
