# Generated by Django 3.1 on 2020-10-12 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0020_auto_20201008_0934"),
        ("workshops", "0019_auto_20201008_1040"),
    ]

    operations = []
