# Generated by Django 3.1 on 2020-10-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0022_auto_20201012_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
