# Generated by Django 3.1.2 on 2020-10-13 09:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0023_workshop_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingblockinstance',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='buildingblocktemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='created_by',
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('building_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historic_data', to='workshops.buildingblocktemplate')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historic_data', to='workshops.workshop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
