# Generated by Django 3.1 on 2020-10-08 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scouts_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": (("access_disabled_entities", "Access disabled entities"),)},
        ),
    ]
